[2023-06-23 22:01:14,379] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_three 2023-06-23T21:30:32.912877+00:00 [failed]>
[2023-06-23 22:01:14,441] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_three 2023-06-23T21:30:32.912877+00:00 [failed]>
[2023-06-23 22:01:14,443] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-23 22:01:14,445] {taskinstance.py:1088} INFO - Starting attempt 2 of 1
[2023-06-23 22:01:14,446] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-23 22:01:14,500] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_three> on 2023-06-23T21:30:32.912877+00:00
[2023-06-23 22:01:14,511] {standard_task_runner.py:52} INFO - Started process 6025 to run task
[2023-06-23 22:01:14,529] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_three', '2023-06-23T21:30:32.912877+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpsmkdl8ew', '--error-file', '/tmp/tmpbehsnft0']
[2023-06-23 22:01:14,532] {standard_task_runner.py:77} INFO - Job 21: Subtask task_three
[2023-06-23 22:01:14,692] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_three 2023-06-23T21:30:32.912877+00:00 [running]> on host 7f7a4865b07a
[2023-06-23 22:01:14,875] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_three
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T21:30:32.912877+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-23T21:30:32.912877+00:00
[2023-06-23 22:04:24,051] {local_task_job.py:199} WARNING - State of this instance has been externally set to shutdown. Terminating instance.
[2023-06-23 22:04:24,076] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6025
[2023-06-23 22:04:24,083] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-23 22:04:24,788] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 111, in titles
    soup = BeautifulSoup(html, "html.parser")
  File "/home/airflow/.local/lib/python3.6/site-packages/bs4/__init__.py", line 335, in __init__
    self._feed()
  File "/home/airflow/.local/lib/python3.6/site-packages/bs4/__init__.py", line 478, in _feed
    self.builder.feed(self.markup)
  File "/home/airflow/.local/lib/python3.6/site-packages/bs4/builder/_htmlparser.py", line 380, in feed
    parser.feed(markup)
  File "/usr/local/lib/python3.6/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.6/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.6/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem.lower())
  File "/home/airflow/.local/lib/python3.6/site-packages/bs4/builder/_htmlparser.py", line 176, in handle_endtag
    self.soup.handle_endtag(name)
  File "/home/airflow/.local/lib/python3.6/site-packages/bs4/__init__.py", line 771, in handle_endtag
    self._popToTag(name, nsprefix)
  File "/home/airflow/.local/lib/python3.6/site-packages/bs4/__init__.py", line 688, in _popToTag
    def _popToTag(self, name, nsprefix=None, inclusivePop=True):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-23 22:04:24,811] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=assignment, task_id=task_three, execution_date=20230623T213032, start_date=20230623T220114, end_date=20230623T220424
[2023-06-23 22:04:25,000] {process_utils.py:66} INFO - Process psutil.Process(pid=6025, status='terminated', exitcode=1, started='22:01:14') (6025) terminated with exit code 1
