[2023-06-26 00:01:21,320] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26 00:01:21,437] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26 00:01:21,441] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-26 00:01:21,445] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2023-06-26 00:01:21,448] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-26 00:01:21,538] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2023-06-25T00:00:00+00:00
[2023-06-26 00:01:21,553] {standard_task_runner.py:52} INFO - Started process 32485 to run task
[2023-06-26 00:01:21,598] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2023-06-25T00:00:00+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp85xs3kr7', '--error-file', '/tmp/tmpw0h40a60']
[2023-06-26 00:01:21,603] {standard_task_runner.py:77} INFO - Job 43: Subtask task_zero
[2023-06-26 00:01:21,934] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2023-06-25T00:00:00+00:00 [running]> on host 7f7a4865b07a
[2023-06-26 00:01:22,297] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2023-06-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-25T00:00:00+00:00
[2023-06-26 00:01:22,311] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-26 00:01:22,327] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2023-06-26 00:01:22,439] {subprocess.py:75} INFO - Output:
[2023-06-26 00:01:40,520] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-26 00:01:42,838] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.2)
[2023-06-26 00:01:42,986] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2023-06-26 00:14:55,222] {local_task_job.py:199} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-06-26 00:14:55,271] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 32485
[2023-06-26 00:14:55,292] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-26 00:14:55,298] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2023-06-26 00:14:55,400] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 175, in execute
    output_encoding=self.output_encoding,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-26 00:14:55,445] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=assignment, task_id=task_zero, execution_date=20230625T000000, start_date=20230626T000121, end_date=20230626T001455
[2023-06-26 00:14:55,675] {process_utils.py:66} INFO - Process psutil.Process(pid=32485, status='terminated', exitcode=1, started='00:01:21') (32485) terminated with exit code 1
[2023-06-26 00:14:55,690] {process_utils.py:66} INFO - Process psutil.Process(pid=32487, status='terminated', started='00:01:22') (32487) terminated with exit code None
