[2023-06-26 00:19:58,880] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26 00:19:59,007] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26 00:19:59,010] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-26 00:19:59,015] {taskinstance.py:1088} INFO - Starting attempt 2 of 3
[2023-06-26 00:19:59,019] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-26 00:19:59,121] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2023-06-25T00:00:00+00:00
[2023-06-26 00:19:59,159] {standard_task_runner.py:52} INFO - Started process 32622 to run task
[2023-06-26 00:19:59,202] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2023-06-25T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpzo_m0efm', '--error-file', '/tmp/tmp2dgux6j5']
[2023-06-26 00:19:59,206] {standard_task_runner.py:77} INFO - Job 44: Subtask task_zero
[2023-06-26 00:19:59,501] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2023-06-25T00:00:00+00:00 [running]> on host 7f7a4865b07a
[2023-06-26 00:20:00,391] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2023-06-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-25T00:00:00+00:00
[2023-06-26 00:20:00,407] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-26 00:20:00,416] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2023-06-26 00:20:00,478] {subprocess.py:75} INFO - Output:
[2023-06-26 00:20:19,314] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-06-26 00:20:20,968] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.2)
[2023-06-26 00:20:21,087] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2023-06-26 00:55:23,223] {local_task_job.py:199} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-06-26 00:55:23,265] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 32622
[2023-06-26 00:55:23,284] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-26 00:55:23,288] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2023-06-26 00:55:23,377] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 175, in execute
    output_encoding=self.output_encoding,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-26 00:55:23,430] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=assignment, task_id=task_zero, execution_date=20230625T000000, start_date=20230626T001958, end_date=20230626T005523
[2023-06-26 00:55:23,737] {process_utils.py:66} INFO - Process psutil.Process(pid=32624, status='terminated', started='00:20:00') (32624) terminated with exit code None
[2023-06-26 00:55:23,748] {process_utils.py:66} INFO - Process psutil.Process(pid=32622, status='terminated', exitcode=1, started='00:19:59') (32622) terminated with exit code 1
